version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    volumes:
      - ../../sistema_emergencia:/var/www/html
    networks:
      - mi_red

  mysql:
    image: mysql:8.4.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'tu'
      MYSQL_DATABASE: emergencia_db
    volumes:
      - ../../sistema_emergencia/db_emergencia.sql:/docker-entrypoint-initdb.d/db_emergencia.sql
    networks:
      - mi_red

networks:
  mi_red:
