services:
  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    volumes:
      - ../../sistema_emergencia:/var/www/html
    networks:
      - mi_red

  mysql:
    image: mysql:8.4.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'tu'
      MYSQL_DATABASE: emergencia_db
    volumes:
      - ../../sistema_emergencia/db_emergencia.sql:/docker-entrypoint-initdb.d/db_emergencia.sql
    networks:
      - mi_red

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: 'tu'
    networks:
      - mi_red

  mkdocs:
    image: python:3.8
    volumes:
      - ../../sistema_emergencia/docs:/docs
    working_dir: /docs
    command: bash -c "pip install mkdocs mkdocs-with-pdf mkdocs-material && mkdocs serve --dev-addr=0.0.0.0:8000"
    ports:
      - "8000:8000"
    networks:
      - mi_red
networks:
  mi_red:
